-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) TOTAL_SALES
FROM BOOK B JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 01
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY  B.AUTHOR_ID ASC, B.CATEGORY DESC

# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE * SUM(BST.TOT_SALE) TOTAL_SALES
# FROM BOOK B JOIN AUTHOR A
# ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN
# (SELECT BS.BOOK_ID, SUM(BS.SALES) TOT_SALE
# FROM BOOK_SALES BS
# WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
# GROUP BY BS.BOOK_ID) BST
# ON B.BOOK_ID = BST.BOOK_ID
# GROUP BY B.AUTHOR_ID, B.CATEGORY
# ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC